name: Testing Github Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=3584
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Print Secrets
        run: echo "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Install NPM Dependencies
        run: yarn install --ignore-engines

      - name: Build Packages
        run: yarn build --concurrency=2
